url: http://127.0.0.1:8066

swagger_open: true

dev_fresh: 1

path:
#  log_folder: "D:/Data/KWeb/storage/log/"
#  runtime_folder: "D:/Data/KWeb/storage/runtime/"

# 调试模式
dev:
    # 调试模式最终监听的端口，默认为8070
    port: 8070
    # 后端调试模式配置
    backend:
        # 调试模式后端更新时间，如果文件变更，等待3s才进行一次更新，能让频繁保存变更更为顺畅, 默认1s
        refresh_time: 3
        # 后端监听端口，默认8072
        port: 8072
        # 监听文件夹地址，为空或者不填默认为AppFolder
        monitor_folder: ""
    # 前端调试模式配置
    frontend:
        # 前端监听端口, 默认8071
        port: 8071
